#pragma once

#define PUMP_PIN 17

#define BLYNK_PIN_POWER V0
#define BLYNK_PIN_STATE_DISABLED V1
#define BLYNK_PIN_STATE_WAITING V2
#define BLYNK_PIN_STATE_PUMPING V3
#define BLYNK_PIN_STATE_COMPLETION V4

#define BLYNK_PIN_PUMP_TIME_MINS V10
#define BLYNK_PIN_WAIT_TIME_MINS V11

#define BLYNK_PIN_RESET_WAIT V21
#define BLYNK_PIN_RESET_PUMP V20
#define BLYNK_PIN_SYNC V22

#define BLYNK_PIN_GRAPH_PUMP_ON V6
